// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PnNS05QFE2QcjlyR4mN3H2Z0H0U15ts',
    appId: '1:131392413265:web:1c380fe82f4e63422c6270',
    messagingSenderId: '131392413265',
    projectId: 'azuracastadmin',
    authDomain: 'azuracastadmin.firebaseapp.com',
    storageBucket: 'azuracastadmin.firebasestorage.app',
    measurementId: 'G-LCFCXG6VYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsH-0aCFCtRaLWFbdD_zWpy4GRxDZ5szw',
    appId: '1:131392413265:android:adf0f6cc7ca9b4ba2c6270',
    messagingSenderId: '131392413265',
    projectId: 'azuracastadmin',
    storageBucket: 'azuracastadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrlFyrEsXWtkxO_wxB_dQLDrkpHvWs8fQ',
    appId: '1:131392413265:ios:9f11dc0e87e365f22c6270',
    messagingSenderId: '131392413265',
    projectId: 'azuracastadmin',
    storageBucket: 'azuracastadmin.firebasestorage.app',
    iosBundleId: 'gr.techzombie.azuracastadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrlFyrEsXWtkxO_wxB_dQLDrkpHvWs8fQ',
    appId: '1:131392413265:ios:9f11dc0e87e365f22c6270',
    messagingSenderId: '131392413265',
    projectId: 'azuracastadmin',
    storageBucket: 'azuracastadmin.firebasestorage.app',
    iosBundleId: 'gr.techzombie.azuracastadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7PnNS05QFE2QcjlyR4mN3H2Z0H0U15ts',
    appId: '1:131392413265:web:aa1794854cbcad6d2c6270',
    messagingSenderId: '131392413265',
    projectId: 'azuracastadmin',
    authDomain: 'azuracastadmin.firebaseapp.com',
    storageBucket: 'azuracastadmin.firebasestorage.app',
    measurementId: 'G-T26267PNRK',
  );
}
